### Criação da base de dados sem valores faltantes e com variável dependente

In [1]:
import pandas  as pandas 
import pyreadstat  as prs
import numpy as np

###  O  dataset de professores

In [2]:
pathTeach='00-Bases-de-dados/Professores/CY07_MSU_TCH_QQQ.sav'

In [3]:
professoresDataSet, infoProfessores=prs.read_sav(pathTeach)

In [4]:
professoresDataSet

,CNTRYID,CNT,CNTSCHID,CNTTCHID,TEACHERID,CYC,NatCen,Region,STRATUM,SUBNATIO,...,FEEDBINSTR,TCATTIMM,GCTRAIN,TCMCEG,GCSELF,W_SCHGRNRABWT,W_FSTUWT_SCH_SUM,VER_DAT,BOOKID,test
0,8.0,ALB,800057.0,800001.0,5.0,07MS,000800,800.0,ALB0203,0080000,...,NaN,NaN,NaN,NaN,NaN,3.45567,93.30319,09MAY19:11:21:10,NaN,NaN
1,8.0,ALB,800121.0,800002.0,5.0,07MS,000800,800.0,ALB0107,0080000,...,NaN,NaN,NaN,NaN,NaN,6.07334,12.46632,09MAY19:11:21:10,NaN,NaN
2,8.0,ALB,800140.0,800003.0,5.0,07MS,000800,800.0,ALB0101,0080000,...,NaN,NaN,NaN,NaN,NaN,3.76885,99.20152,09MAY19:11:21:10,NaN,NaN
3,8.0,ALB,800149.0,800004.0,5.0,07MS,000800,800.0,ALB0211,0080000,...,NaN,NaN,NaN,NaN,NaN,6.62948,19.88845,09MAY19:11:21:10,NaN,NaN
4,8.0,ALB,800095.0,800005.0,5.0,07MS,000800,800.0,ALB0204,0080000,...,NaN,NaN,NaN,NaN,NaN,3.35644,104.76897,09MAY19:11:21:10,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107362,840.0,USA,84000013.0,84003775.0,NaN,07MS,084000,84000.0,USA0308,8400000,...,NaN,NaN,NaN,NaN,NaN,62.11108,25536.12489,30APR19:15:44:51,NaN,NaN
107363,840.0,USA,84000077.0,84003776.0,4.0,07MS,084000,84000.0,USA0206,8400000,...,0.6190,NaN,NaN,NaN,NaN,37.25790,18158.99614,30APR19:15:44:51,NaN,NaN
107364,840.0,USA,84000035.0,84003777.0,4.0,07MS,084000,84000.0,USA0206,8400000,...,-0.1045,NaN,NaN,NaN,NaN,41.09023,20136.85144,30APR19:15:44:51,NaN,NaN
107365,840.0,USA,84000051.0,84003778.0,5.0,07MS,084000,84000.0,USA0205,8400000,...,NaN,NaN,NaN,NaN,NaN,115.66924,49343.58053,30APR19:15:44:51,NaN,NaN
107366,840.0,USA,84000123.0,84003779.0,4.0,07MS,084000,84000.0,USA0104,8400000,...,1.5975,NaN,NaN,NaN,NaN,55.83552,34010.36443,30APR19:15:44:51,NaN,NaN

### Selecionando somente as perguntas que tem algumas resposta e o código do  país

In [5]:
professoresDF = professoresDataSet[['TC001Q01NA','TC002Q01NA','TC186Q01HA','TC005Q01NA','TC007Q01NA','TC007Q02NA','TC188Q01HA','TC014Q01HA','TC015Q01NA','TC018Q01NA','TC018Q01NB','TC018Q02NA','TC018Q02NB','TC018Q03NA','TC018Q03NB','TC018Q04NA','TC018Q04NB','TC018Q05NA','TC018Q05NB','TC018Q06NA','TC018Q06NB','TC018Q07NA','TC018Q07NB','TC018Q08NA','TC018Q08NB','TC018Q09NA','TC018Q09NB','TC018Q10NA','TC018Q10NB','TC018Q11NA','TC018Q11NB','TC045Q01NA','TC045Q01NB','TC045Q02NA','TC045Q02NB','TC045Q03NA','TC045Q03NB','TC045Q04NA','TC045Q04NB','TC045Q05NA','TC045Q05NB','TC045Q06NA','TC045Q06NB','TC045Q07NA','TC045Q07NB','TC045Q08NA','TC045Q08NB','TC045Q09NA','TC045Q09NB','TC045Q10NA','TC045Q10NB','TC045Q11NA','TC045Q11NB','TC045Q12NA','TC045Q12NB','TC045Q13NA','TC045Q13NB','TC045Q14NA','TC045Q14NB','TC045Q15NA','TC045Q15NB','TC045Q16HA','TC045Q16HB','TC045Q17HA','TC045Q17HB','TC045Q18HA','TC045Q18HB','TC021Q01NA','TC193Q01HA','TC193Q02HA','TC193Q03HA','TC193Q04HA','TC193Q05HA','TC020Q01NA','TC020Q02NA','TC020Q03NA','TC020Q04NA','TC020Q05NA','TC020Q06NA','TC175Q01HA','TC198Q01HA','TC198Q02HA','TC198Q03HA','TC198Q04HA','TC198Q05HA','TC198Q06HA','TC198Q07HA','TC198Q08HA','TC198Q09HA','TC198Q10HA','TC199Q01HA','TC199Q02HA','TC199Q03HA','TC199Q04HA','TC199Q05HA','TC199Q06HA','TC199Q07HA','TC199Q08HA','TC199Q09HA','TC199Q10HA','TC199Q11HA','TC199Q12HA','TC046Q04NA','TC046Q05NA','TC046Q06NA','TC046Q07NA','TC028Q01NA','TC028Q02NA','TC028Q03NA','TC028Q04NA','TC028Q05NA','TC028Q06NA','TC028Q07NA','TC028Q08NA','TC152Q01HA','TC152Q02HA','TC152Q03HA','TC152Q04HA','TC155Q02HA','TC155Q03HA','TC155Q04HA','TC155Q05HA','TC155Q06HA','TC155Q07HA','TC166Q01HA','TC166Q02HA','TC166Q03HA','TC166Q04HA','TC166Q05HA','TC166Q06HA','TC166Q07HA','TC164Q01HA','TC169Q01HA','TC169Q02HA','TC169Q03HA','TC169Q04HA','TC169Q05HA','TC169Q06HA','TC169Q07HA','TC169Q08HA','TC169Q09HA','TC169Q10HA','TC169Q11HA','TC169Q12HA','TC169Q13HA','TC169Q14HA','TC184Q01HA','TC054Q01NA','TC054Q02NA','TC054Q03NA','TC054Q04NA','TC054Q05NA','TC054Q06NA','TC054Q07NA','TC192Q01HA','TC192Q02HA','TC192Q03HA','TC192Q04HA','TC192Q05HA','TC176Q01HA','TC176Q02HA','TC176Q03HA','TC176Q05HA','TC176Q06HA','TC176Q07HA','TC172Q01HA','TC173Q01HA','CNT']]

In [6]:
professoresDF

,TC001Q01NA,TC002Q01NA,TC186Q01HA,TC005Q01NA,TC007Q01NA,TC007Q02NA,TC188Q01HA,TC014Q01HA,TC015Q01NA,TC018Q01NA,...,TC192Q05HA,TC176Q01HA,TC176Q02HA,TC176Q03HA,TC176Q05HA,TC176Q06HA,TC176Q07HA,TC172Q01HA,TC173Q01HA,CNT
0,1.0,40.0,1.0,1.0,10.0,10.0,1.0,2.0,1.0,1.0,...,3.0,4.0,3.0,4.0,4.0,3.0,4.0,2.0,2.0,ALB
1,2.0,26.0,1.0,1.0,5.0,5.0,1.0,1.0,1.0,0.0,...,2.0,4.0,4.0,4.0,4.0,4.0,4.0,2.0,4.0,ALB
2,2.0,38.0,1.0,1.0,11.0,16.0,1.0,2.0,1.0,0.0,...,3.0,4.0,5.0,5.0,4.0,4.0,4.0,3.0,5.0,ALB
3,1.0,42.0,1.0,1.0,2.0,3.0,1.0,2.0,1.0,0.0,...,3.0,2.0,3.0,4.0,4.0,2.0,4.0,2.0,3.0,ALB
4,1.0,30.0,1.0,1.0,5.0,5.0,1.0,1.0,1.0,0.0,...,3.0,5.0,5.0,5.0,5.0,4.0,5.0,2.0,3.0,ALB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USA
107363,1.0,40.0,NaN,1.0,5.0,5.0,NaN,2.0,1.0,1.0,...,NaN,5.0,4.0,5.0,5.0,2.0,5.0,4.0,5.0,USA
107364,1.0,34.0,NaN,1.0,14.0,14.0,NaN,2.0,3.0,1.0,...,NaN,5.0,4.0,4.0,5.0,4.0,5.0,4.0,3.0,USA
107365,1.0,45.0,2.0,1.0,2.0,12.0,NaN,1.0,1.0,0.0,...,3.0,5.0,4.0,4.0,5.0,1.0,4.0,2.0,3.0,USA
107366,1.0,47.0,NaN,1.0,2.0,4.0,NaN,2.0,1.0,1.0,...,NaN,5.0,3.0,4.0,4.0,4.0,5.0,4.0,2.0,USA

### Eliminando instâncias com algum valor nulo

In [7]:
professoresDF.dropna(inplace=True)

/home/rochelly/.local/lib/python3.7/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

### Classificando classificando os  resultado em nível baixo (até  3) e alto(maior que 3) de acordo com as notas e níveis de proficiência fornecidos pela OCDE

In [8]:
dicNivelCiencias = {'ALB': 'Alta' ,
'QAZ':'Alta',
'BRA':'Baixa',
'CHL':'Alta',
'TAP':'Alta',
'DOM':'Baixa',
'DEU':'Alta',
'HKG':'Alta',
'KOR':'Alta',
'MAC':'Alta',
'MYS':'Alta',
'MAR':'Baixa',
'PAN':'Baixa',
'PER':'Baixa',
'PRT':'Alta',
'ESP':'Alta',
'ARE':'Alta',
'GBR':'Alta'}

In [9]:
dicNivelMatematica = {'ALB': 'Baixa' ,
'QAZ':'Baixa',
'BRA':'Baixa',
'CHL':'Baixa',
'TAP':'Alta',
'DOM':'Baixa',
'DEU':'Alta',
'HKG':'Alta',
'KOR':'Alta',
'MAC':'Alta',
'MYS':'Baixa',
'MAR':'Baixa',
'PAN':'Baixa',
'PER':'Baixa',
'PRT':'Alta',
'ESP':'Alta',
'ARE':'Baixa',
'GBR':'Alta'}

###  Mapeado para o país

In [10]:
professoresDF['nivelMatematica'] = professoresDF['CNT'].map(dicNivelMatematica)

/home/rochelly/.local/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [11]:
professoresDF['nivelCiencias'] = professoresDF['CNT'].map(dicNivelCiencias)

/home/rochelly/.local/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [12]:
professoresDF

,TC001Q01NA,TC002Q01NA,TC186Q01HA,TC005Q01NA,TC007Q01NA,TC007Q02NA,TC188Q01HA,TC014Q01HA,TC015Q01NA,TC018Q01NA,...,TC176Q02HA,TC176Q03HA,TC176Q05HA,TC176Q06HA,TC176Q07HA,TC172Q01HA,TC173Q01HA,CNT,nivelMatematica,nivelCiencias
0,1.0,40.0,1.0,1.0,10.0,10.0,1.0,2.0,1.0,1.0,...,3.0,4.0,4.0,3.0,4.0,2.0,2.0,ALB,Baixa,Alta
1,2.0,26.0,1.0,1.0,5.0,5.0,1.0,1.0,1.0,0.0,...,4.0,4.0,4.0,4.0,4.0,2.0,4.0,ALB,Baixa,Alta
2,2.0,38.0,1.0,1.0,11.0,16.0,1.0,2.0,1.0,0.0,...,5.0,5.0,4.0,4.0,4.0,3.0,5.0,ALB,Baixa,Alta
3,1.0,42.0,1.0,1.0,2.0,3.0,1.0,2.0,1.0,0.0,...,3.0,4.0,4.0,2.0,4.0,2.0,3.0,ALB,Baixa,Alta
4,1.0,30.0,1.0,1.0,5.0,5.0,1.0,1.0,1.0,0.0,...,5.0,5.0,5.0,4.0,5.0,2.0,3.0,ALB,Baixa,Alta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103819,2.0,63.0,1.0,1.0,18.0,39.0,2.0,2.0,1.0,0.0,...,4.0,5.0,5.0,2.0,5.0,4.0,3.0,GBR,Alta,Alta
103825,1.0,49.0,1.0,2.0,14.0,14.0,1.0,1.0,1.0,1.0,...,5.0,5.0,4.0,3.0,4.0,2.0,2.0,GBR,Alta,Alta
103828,1.0,42.0,1.0,1.0,6.0,17.0,1.0,1.0,1.0,0.0,...,3.0,4.0,4.0,2.0,4.0,2.0,3.0,GBR,Alta,Alta
103831,2.0,25.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,...,4.0,4.0,4.0,3.0,4.0,1.0,3.0,GBR,Alta,Alta
103833,2.0,59.0,1.0,1.0,20.0,35.0,1.0,1.0,1.0,0.0,...,4.0,5.0,4.0,2.0,4.0,2.0,5.0,GBR,Alta,Alta

### Exportando  o novo  dataset completo

In [13]:
professoresDF.to_csv('00-Bases-de-dados/Professores- X-Niveis/pisa-professores-niveis.csv')

In [14]:
professoresDF['nivelCiencias'].unique()

array(['Alta', 'Baixa'], dtype=object)

In [15]:
professoresDF['nivelMatematica'].unique()

array(['Baixa', 'Alta'], dtype=object)